### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/browser_launcher#42]
I'm seeing two test failures on the CI:

```
❌ test/chrome_test.dart: (headless: false) chrome with user data dir and signIn = false has correct profile path (failed)
  Expected: not null
    Actual: <null>
  
  package:matcher               expect
  test/chrome_test.dart 43:5    main.connectToTab
  ===== asynchronous gap ===========================
  test/chrome_test.dart 177:39  main.<fn>.<fn>.<fn>.<fn>
❌ test/chrome_test.dart: (headless: false) chrome with user data dir and signIn = true has correct profile path (failed)
  Expected: not null
    Actual: <null>
  
  package:matcher               expect
  test/chrome_test.dart 43:5    main.connectToTab
  ===== asynchronous gap ===========================
  test/chrome_test.dart 177:[39](https://github.com/dart-lang/browser_launcher/actions/runs/4581180906/jobs/8090517085?pr=41#step:8:41)  main.<fn>.<fn>.<fn>.<fn>
```

**Comment by devoncarew** [comment]
Still seeing these: https://github.com/dart-lang/browser_launcher/pull/43

**Comment by devoncarew** [comment]
cc @elliette  as well

**Comment by elliette** [comment]
Thanks! Will take a look

**Comment by elliette** [comment]
I see what's happening, not sure the best way to fix the test. 

We are opening `chrome://version/`, but prefixing it with `/json/new?` (see: https://github.com/dart-lang/browser_launcher/blob/master/test/chrome_test.dart#L195), so really we are trying to open `/json/new?chrome://version/`. This never opens and we get back the response code 405: Method not allowed error. 

I'm not sure why we are pre-fixing chrome://version with `/json/new?`. @annagrin, I see you added that in https://github.com/dart-lang/browser_launcher/pull/29, do you mind looking?

One final note is if we remove `/json/new?` and just try to open `chrome://version/`, this fails with the following error:         https://github.com/dart-lang/sdk/blob/73dea244cc94dc7dbc00a751b2c3151797f4b836/sdk/lib/_http/http_impl.dart#L2755) It looks like the Dart HTTP client only accepts `http` and `https` scheme (not `chrome` scheme).

**Comment by annagrin** [comment]
It seems that something changed in chrome, and now `/json/new` is not allowed with `chrome:` uris. It used to work, and still does for non-chrome uris...  I unfortunately don't know another way to navigate to a `chrome://version` page (or any other) from `chrome!.chromeConnection.`  

@elliette @devoncarew if you know a way I'd love to learn! If not, we can just disable these tests for now, like I already did in webdev.
